### ISSUE TITLE
[Bug Report] - Additional "AnonymousSchema" php classes after code generation

### ISSUE THREAD

**Issue by andreadangel1** [nickshoe/asyncapi-php-template#4]
**Environment details**
-PHP version: 8.1.16

**Description**
After the php code generation, it will be created a class named "AnonymousSchema" for every schema that inherits its properties from another one.

**Example**
I have two object-type schemas into the asyncapi .yaml file:
```
DomainEvent:
      type: object
      discriminator: _type
      required:
        - _type
        - id
        - createdAt
      properties:
        _type:
          type: string
          readOnly: true
        id:
          type: string
          readOnly: true
        createdAt:
          type: string
          format: date-time
          example: '2012-04-23T18:25:43.511Z'
          readOnly: true
    UserPasswordResetEvent:
      description: A user password reset event.
      allOf:
        - $ref: "#/components/schemas/DomainEvent"
        - type: object
          required:
            - user
            - tempPassword
          properties:
            user:
              $ref: "#/components/schemas/User"
            tempPassword:
              type: string
```
In this example, "UserPasswordResetEvent" inherits its properties from "DomainEvent".
After generating the "UserPasswordResetEvent" php class, it will be created another php class named "AnonymousSchema8.class.php". The last one is identical to the first one, exept for missing the hereditariness from "AnonymousSchema8.class.php" and "DomainEvent.class.php"

**Comment by nickshoe** [comment]
resolved in v0.2.10-0
